tap "adoptopenjdk/openjdk"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "mircomacrelli/casks"
brew "jpeg"
brew "atomicparsley"
brew "brightness"
brew "python@3.8"
brew "doctl"
brew "sdl2"
brew "ffmpeg"
brew "git"
brew "gnupg"
brew "imagemagick"
brew "iperf"
brew "mas"
brew "node"
brew "pinentry-mac"
brew "ruby"
brew "trash"
brew "vim"
brew "youtube-dl"
brew "zsh"
cask "adoptopenjdk14"
cask "alfred"
cask "arq"
cask "audacity"
cask "audio-hijack"
cask "bbedit"
cask "bettertouchtool"
cask "calibre"
cask "camo-studio"
cask "charles"
cask "cleanmymac"
cask "coconutbattery"
cask "daisydisk"
cask "dash"
cask "displaycal"
cask "dosbox"
cask "drivedx"
cask "font-awesome-5-pro"
cask "gemini"
cask "gog-galaxy"
cask "handbrake"
cask "hopper-disassembler"
cask "hp-connectivity-kit"
cask "hp-prime"
cask "ibm-vga-8x16"
cask "imagealpha"
cask "imageoptim"
cask "intellij-idea"
cask "keyboardcleantool"
cask "makemkv"
cask "monodraw"
cask "mp4tools"
cask "musicbrainz-picard"
cask "openemu-experimental"
cask "paw"
cask "pgmodeler"
cask "postgres"
cask "pragmatapro"
cask "raspberry-pi-imager"
cask "retrobatch"
cask "soulver"
cask "steam"
cask "synalyze-it-pro"
cask "transmission"
cask "transmit"
cask "vlc"
cask "vmware-fusion"
cask "vuescan"
cask "wireshark"
cask "xld"
cask "xscope"
mas "1Blocker", id: 1107421413
mas "1Password 7", id: 1333542190
mas "Fantastical", id: 975937182
mas "Image2icon", id: 992115977
mas "Keka", id: 470158793
mas "KeyKey", id: 1035137927
mas "Keynote", id: 409183694
mas "Money Pro", id: 972572731
mas "Name Mangler", id: 603637384
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "PCalc", id: 403504866
mas "Pixelmator Pro", id: 1289583905
mas "Reeder", id: 1529448980
mas "Simple Comic", id: 1497435571
mas "Taskheat", id: 1431995750
mas "Time Sink", id: 404363161
mas "WireGuard", id: 1451685025
mas "Xcode", id: 497799835
