source 'https://rubygems.org' do
  gem 'dropbox_api'
  gem 'jekyll'
  gem 'ruby-progressbar'
  gem 'ansi'
  gem 'rubyzip'
  gem 'nokogiri'
  gem 'rubocop'
  gem 'debase'
  gem 'ruby-debug-ide'
  gem 'cocoapods'
end
